//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongConvert.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SongConvert.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background processing cancelled..
        /// </summary>
        internal static string MainForm_backgroundWorker1_RunWorkerCompleted_Background_processing_cancelled_ {
            get {
                return ResourceManager.GetString("MainForm_backgroundWorker1_RunWorkerCompleted_Background_processing_cancelled_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background processing completed in approximately {0} milliseconds..
        /// </summary>
        internal static string MainForm_backgroundWorker1_RunWorkerCompleted_Background_processing_completed_in_approximately__0__milliseconds_ {
            get {
                return ResourceManager.GetString("MainForm_backgroundWorker1_RunWorkerCompleted_Background_processing_completed_in_" +
                        "approximately__0__milliseconds_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background processing completed with errors: {0}.
        /// </summary>
        internal static string MainForm_backgroundWorker1_RunWorkerCompleted_Background_processing_completed_with_errors___0_ {
            get {
                return ResourceManager.GetString("MainForm_backgroundWorker1_RunWorkerCompleted_Background_processing_completed_wit" +
                        "h_errors___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string MainForm_backgroundWorker1_RunWorkerCompleted_Cancelled {
            get {
                return ResourceManager.GetString("MainForm_backgroundWorker1_RunWorkerCompleted_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string MainForm_backgroundWorker1_RunWorkerCompleted_Complete {
            get {
                return ResourceManager.GetString("MainForm_backgroundWorker1_RunWorkerCompleted_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR!.
        /// </summary>
        internal static string MainForm_backgroundWorker1_RunWorkerCompleted_ERROR_ {
            get {
                return ResourceManager.GetString("MainForm_backgroundWorker1_RunWorkerCompleted_ERROR_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a valid destination.
        /// </summary>
        internal static string MainForm_convertButton_Click_You_must_specify_a_valid_destination {
            get {
                return ResourceManager.GetString("MainForm_convertButton_Click_You_must_specify_a_valid_destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify the path to the EasyWorship song database!.
        /// </summary>
        internal static string MainForm_convertButton_Click_You_must_specify_the_path_to_the_EasyWorship_song_database_ {
            get {
                return ResourceManager.GetString("MainForm_convertButton_Click_You_must_specify_the_path_to_the_EasyWorship_song_da" +
                        "tabase_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the destination folder.
        /// </summary>
        internal static string MainForm_destinationBrowseButton_Click_Please_select_the_destination_folder {
            get {
                return ResourceManager.GetString("MainForm_destinationBrowseButton_Click_Please_select_the_destination_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the EasyWorship song database folder.
        /// </summary>
        internal static string MainForm_easyWorshipBrowseButton_Click_Please_select_the_EasyWorship_song_database_folder {
            get {
                return ResourceManager.GetString("MainForm_easyWorshipBrowseButton_Click_Please_select_the_EasyWorship_song_databas" +
                        "e_folder", resourceCulture);
            }
        }
    }
}
